services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bookrating:1.5
    container_name: app
    restart: unless-stopped
    ports:
      - "89:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    restart: unless-stopped
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
