services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    webserver:
        image: nginx:latest
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - laravel

    db:
        image: postgres:15
        container_name: db
        restart: unless-stopped
        ports:
            - "5444:5432"
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: laravel_password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel


    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel


    mailhog:
        image: axllent/mailpit:latest
        container_name: mailhog
        restart: unless-stopped
        ports:
            - "1025:1025"  # SMTP server
            - "8025:8025"  # Web UI
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    postgres_data:
